enum audit_log_action {
  create
  update
  delete
}

enum feedback_status_enum {
  pending
  inprogress
  complete
  incomplete
}

enum feedback_type_enum {
  feature
  general
  testimonial
  issue
}

enum fileType {
  image
  document
  video
  audio
}

enum occurance_frequency_enum {
  Daily
  Weekly
  Monthly
  Yearly
}

table account_types {
  id text [pk, not null]
  name text [not null]
  sortOrder integer [not null, default: 0]
}

table accounts {
  id text [pk, not null]
  type text [not null]
  name text
  balance numeric [not null, default: '0.00']
  currency text [not null, default: 'USD']
  useForNetWorth boolean [not null, default: true]
  monthlyBudget numeric
  isPrivate boolean [not null, default: false]
  icon text
  color text
  bankAccountOwnerName text
  bankAccountNumber text
  bankAccountType text
  bankIban text
  bankName text
  bankRouting text
  bankSwiftCode text
  cardExpiryDate date
  cardHolderName text
  cardLimit numeric
  cardMonthlyDueDate integer
  cardMonthlyStatementDate integer
  cardNumber text
  cardType text
  loanEndDate date
  loanInterestRate numeric
  loanMonthlyDueDate integer
  loanStartDate date
  groupId text [not null]
  creatorId text [not null]
  createdAt "timestamp with time zone" [default: `now()`]
  updatedAt "timestamp with time zone"
}

table admins {
  id text [pk, not null]
  name text
  email text [not null]
  password text [not null]
  lastLogin "timestamp with time zone"
  bannedAt "timestamp with time zone"
  verifiedAt "timestamp with time zone"
  createdAt "timestamp with time zone" [default: `now()`]
  updatedAt "timestamp with time zone"

  indexes {
    email [name: 'adminEmailUniqueIndex', unique]
  }
}

table audit_logs {
  id text [pk, not null]
  entity varchar(100) [not null]
  entityId varchar(100) [not null]
  creatorId varchar(100) [not null]
  groupId varchar(100)
  action audit_log_action [not null]
  previousData jsonb [default: `{}`]
  updatedData jsonb [default: `{}`]
  createdAt "timestamp with time zone" [default: `now()`]
}

table balance_transfer_schedules {
  id text [pk, not null]
  fromAccountId text [not null]
  toAccountId text [not null]
  amount numeric [not null]
  title text
  note text
  categoryId text
  subcategoryId text
  creatorId text
  groupId text [not null]
  cronExpression text [not null]
  nextOccurrenceAt "timestamp with time zone" [not null]
  stopOccurrenceAt "timestamp with time zone"
  occurrencesTotal integer
  occurrencesDone integer [not null, default: 0]
  createdAt "timestamp with time zone" [default: `now()`]
  updatedAt "timestamp with time zone"
}

table balance_transfers {
  id text [pk, not null]
  fromAccountId text [not null]
  toAccountId text [not null]
  amount numeric [not null]
  title text
  note text
  committedAt "timestamp with time zone" [not null]
  outTransactionId text
  inTransactionId text
  categoryId text
  subcategoryId text
  creatorId text
  groupId text [not null]
  createdAt "timestamp with time zone" [default: `now()`]
  updatedAt "timestamp with time zone"
}

table categories {
  id text [pk, not null]
  name text [not null]
  icon text
  color text
  sortOrder integer [not null, default: 0]
  groupId text
  creatorId text
}

table currencies {
  id text [pk, not null]
  name text [not null]
  sortOrder integer [not null, default: 0]
  symbol text [default: '$']
  conversionRateUSD numeric [not null, default: '1.00']
  groupId text
  creatorId text
}

table feedback {
  id text [pk, not null]
  feedbackText text [not null]
  feedbackType feedback_type_enum
  status feedback_status_enum [default: 'pending']
  activePage text
  fileUrls text[]
  creatorId text
  createdAt "timestamp with time zone" [default: `now()`]
  updatedAt "timestamp with time zone"
}

table groups {
  id text [pk, not null]
  name text [not null]
  email text
  phone text
  address1 text
  address2 text
  city text
  state text
  country text
  zip text
  creatorId text
  verifiedOn "timestamp with time zone"
  subscriptionId text
  createdAt "timestamp with time zone" [default: `now()`]
  updatedAt "timestamp with time zone"
}

table invites {
  id text [pk, not null]
  email text [not null]
  groupId text [not null]
  roleId text
  invitedBy text [not null]
  invitedOn "timestamp with time zone" [not null, default: `now()`]
  acceptedOn "timestamp with time zone"
}

table memberships {
  userId text [not null]
  groupId text [not null]
  roleId text

  indexes {
    (userId, groupId) [pk]
  }
}

table pricing_plan {
  id text [pk, not null]
  name text [not null]
  description text
  monthlyPrice integer [not null]
  yearlyPrice integer [not null]
  discountPrice integer
  discountPeriodStart date
  discountPeriodEnd date
  currency text [not null, default: 'USD']
  isActive boolean [not null, default: false]
  storageLimit bigint [not null]
  maxUsers integer [not null]
  activeFeatures text[]
  inactiveFeatures text[]
  trialPeriodDays integer
  createdAt "timestamp with time zone" [default: `now()`]
  updatedAt "timestamp with time zone"
}

table referrals {
  id text [pk, not null]
  referralCodeId text [not null]
  referredId text
  points integer [not null, default: 0]
  createdAt "timestamp with time zone" [default: `now()`]
  updatedAt "timestamp with time zone"
}

table referral_codes {
  id text [pk, not null]
  userId text [not null]
  groupId text [not null]
  referralCode text [not null, unique]
  createdAt "timestamp with time zone" [default: `now()`]
  updatedAt "timestamp with time zone"
}

table roles {
  id text [pk, not null]
  name text [not null]
  description text
  groupId text
  permissions text
  createdAt "timestamp with time zone" [default: `now()`]
  updatedAt "timestamp with time zone"
}

table storage {
  id text [pk, not null]
  filename text
  url text
  type fileType [default: 'image']
  extension text
  size integer [default: 0]
  groupId text [not null]
  uploadedBy text
  entityName text
  createdAt "timestamp with time zone" [default: `now()`]
  updatedAt "timestamp with time zone"
}

table subcategories {
  id text [pk, not null]
  name text [not null]
  icon text
  color text
  sortOrder integer [not null, default: 0]
  groupId text
  creatorId text
  categoryId text
}

table subscriptions {
  id text [pk, not null]
  groupId text [not null, unique]
  planId text [not null]
  creatorId text
  startDate "timestamp with time zone" [not null]
  endDate "timestamp with time zone"
  isTrial boolean [not null, default: false]
  autoRenewal boolean [not null, default: false]
  paymentMethod text
  transactionId text
  usedStorage integer [not null, default: 0]
  approvedAt "timestamp with time zone"
  approverId text
  billingIntervalMonths integer [not null, default: 1]
  history jsonb [not null, default: '{}']
  createdAt "timestamp with time zone" [default: `now()`]
  updatedAt "timestamp with time zone"
}

table transaction_schedules {
  id text [pk, not null]
  accountId text [not null]
  amount numeric [not null]
  title text
  note text
  isOutgoing boolean [not null, default: true]
  categoryId text
  subcategoryId text
  creatorId text
  groupId text [not null]
  occuranceFrequency occurance_frequency_enum [not null]
  onDayOfWeek integer
  onDayOfMonth integer
  onMonthOfYear integer
  nextOccurrenceAt "timestamp with time zone" [not null]
  stopOccurrenceAt "timestamp with time zone"
  occurrencesTotal integer [not null, default: -1]
  occurrencesDone integer [not null, default: 0]
  createdAt "timestamp with time zone" [default: `now()`]
  updatedAt "timestamp with time zone"
}

table transactions {
  id text [pk, not null]
  accountId text [not null]
  amount numeric [not null]
  title text
  note text
  isOutgoing boolean [not null, default: true]
  categoryId text
  subcategoryId text
  committedAt "timestamp with time zone" [not null, default: `now()`]
  creatorId text
  groupId text [not null]
  scheduledTransactionId text
  createdAt "timestamp with time zone" [default: `now()`]
  updatedAt "timestamp with time zone"
}

table users_settings {
  userId text [not null]
  key text [not null]
  value text [not null]

  indexes {
    (userId, key) [pk]
  }
}

table users {
  id text [pk, not null]
  username text [not null, unique]
  firstName text [not null]
  lastName text [not null]
  defaultGroupId text
  coverPhoto text
  profilePhoto text
  email text
  password text [not null]
  phone text
  address1 text
  address2 text
  city text
  state text
  country text
  zip text
  lastLogin "timestamp with time zone"
  bannedAt "timestamp with time zone"
  verifiedAt "timestamp with time zone"
  createdAt "timestamp with time zone" [default: `now()`]
  updatedAt "timestamp with time zone"
}

ref: accounts.groupId - groups.id

ref: accounts.creatorId - users.id

ref: accounts.type > account_types.id

ref: balance_transfer_schedules.toAccountId - accounts.id

ref: balance_transfer_schedules.categoryId - categories.id

ref: balance_transfer_schedules.creatorId - users.id

ref: balance_transfer_schedules.subcategoryId - subcategories.id

ref: balance_transfer_schedules.groupId - groups.id

ref: balance_transfers.toAccountId - accounts.id

ref: balance_transfers.categoryId - categories.id

ref: balance_transfers.subcategoryId - subcategories.id

ref: balance_transfers.creatorId - users.id

ref: balance_transfers.groupId - groups.id

ref: transactions.id - balance_transfers.outTransactionId

ref: categories.groupId > groups.id

ref: categories.creatorId > users.id

ref: currencies.groupId > groups.id

ref: currencies.creatorId > users.id

ref: users.defaultGroupId - groups.id

ref: subscriptions.groupId - groups.id

ref: invites.groupId > groups.id

ref: invites.invitedBy > users.id

ref: memberships.userId > users.id

ref: memberships.groupId > groups.id

ref: memberships.roleId > roles.id

ref: referrals.referralCodeId > referral_codes.id

ref: referrals.referredId > users.id

ref: referral_codes.userId - users.id

ref: referral_codes.groupId - groups.id

ref: roles.groupId > groups.id

ref: subcategories.groupId > groups.id

ref: subcategories.creatorId > users.id

ref: subcategories.categoryId > categories.id

ref: subscriptions.planId > pricing_plan.id

ref: subscriptions.approverId - users.id

ref: transaction_schedules.accountId - accounts.id

ref: transaction_schedules.categoryId - categories.id

ref: transaction_schedules.subcategoryId - subcategories.id

ref: transaction_schedules.creatorId - users.id

ref: transaction_schedules.groupId - groups.id

ref: transactions.accountId > accounts.id

ref: transactions.categoryId - categories.id

ref: transactions.subcategoryId - subcategories.id

ref: transactions.creatorId - users.id

ref: transactions.groupId > groups.id

ref: transactions.scheduledTransactionId > transaction_schedules.id