import { InsertPlan } from '../../main/plan/plan.schema'

export const SEED_DATA_PLANS: InsertPlan[] = [
    {
        name: 'Free',
        description:
            'Good for individual. Always free. No credit card required.',
        monthlyPrice: 0,
        yearlyPrice: 0,
        storageLimit: 500,
        maxUsers: 1,
        maxCases: 25,
        monthlySmsLimit: 100,
        monthlyAiCredits: 50,
        activeFeatures: [
            'Keep track of 25 cases',
            '500 MB storage',
            '100 SMS per month for custom communication',
            '50 AI credits per month',
            'Unlimited notification by email/SMS',
            'Unlimited case history',
            'Unlimited notes',
            'Unlimited events',
        ],
        inactiveFeatures: [
            'Let clients follow their cases',
            'AI summary of case history',
            'Communication with clients',
        ],
        trialPeriodDays: 0,
        isActive: true,
        currency: 'BDT',
    },
    {
        name: 'Bronze',
        description: 'For growing teams with advanced needs',
        monthlyPrice: 100,
        yearlyPrice: 1100,
        storageLimit: 2 * 1024,
        maxUsers: 3,
        maxCases: 50,
        monthlySmsLimit: 500,
        monthlyAiCredits: 200,
        activeFeatures: [
            'Keep track of 50 cases',
            '2 GB storage',
            '500 SMS per month for custom communication',
            '200 AI credits per month',
            'Unlimited notification by email/SMS',
            'Unlimited case history',
            'Unlimited notes',
            'Unlimited events',
            'Let clients follow their cases',
        ],
        inactiveFeatures: [
            'AI summary of case history',
            'Communication with clients',
        ],
        trialPeriodDays: 0,
        isActive: true,
        currency: 'BDT',
    },
    {
        name: 'Silver',
        description: 'Partner for your growth',
        monthlyPrice: 300,
        yearlyPrice: 3200,
        storageLimit: 10 * 1024,
        maxUsers: 5,
        maxCases: 200,
        monthlySmsLimit: 2000,
        monthlyAiCredits: 500,
        activeFeatures: [
            'Keep track of 200 cases',
            '10 GB storage',
            '2000 SMS per month for custom communication',
            '500 AI credits per month',
            'Unlimited notification by email/SMS',
            'Unlimited case history',
            'Unlimited notes',
            'Unlimited events',
            'Let clients follow their cases',
            'AI summary of case history',
        ],
        inactiveFeatures: ['Communication with clients'],
        isActive: true,
        currency: 'BDT',
    },
    {
        name: 'Gold',
        description: 'For very large teams with advanced needs',
        monthlyPrice: 600,
        yearlyPrice: 6000,
        storageLimit: 25 * 1024,
        maxUsers: 20,
        maxCases: 999999,
        monthlySmsLimit: 999999,
        monthlyAiCredits: 2000,
        activeFeatures: [
            'Keep track of unlimited cases',
            '25 GB storage',
            'Unlimited SMS per month for custom communication',
            '2000 AI credits per month',
            'Unlimited notification by email/SMS',
            'Unlimited case history',
            'Unlimited notes',
            'Unlimited events',
            'Let clients follow their cases',
            'AI summary of case history',
            'Communication with clients',
        ],
        inactiveFeatures: [],
        isActive: true,
        currency: 'BDT',
    },
]
