@resource=accounts
@id=d59d7f428b

###
POST {{BACKEND_URL}}/{{resource}}
Content-Type: application/json
Authorization: Bearer {{TEMP_ACCESS_TOKEN}}

{
  "name": "Chase Sapphire",
  "type": "CreditCard"
}

###
GET {{BACKEND_URL}}/{{resource}}
Content-Type: application/json
Authorization: Bearer {{TEMP_ACCESS_TOKEN}}


###

GET {{BACKEND_URL}}/{{resource}}/{{id}}
Content-Type: application/json
Authorization: Bearer {{TEMP_ACCESS_TOKEN}}

PUT {{BACKEND_URL}}/{{resource}}/{{id}}
Content-Type: application/json
Authorization: Bearer {{TEMP_ACCESS_TOKEN}}

{
  "name": "Chase Sapphire 3"
}

GET {{BACKEND_URL}}/{{resource}}/custom/my
Content-Type: application/json
Authorization: Bearer {{TEMP_ACCESS_TOKEN}}
