POST {{BACKEND_URL}}/accounts
Content-Type: application/json
Authorization: Bearer {{TEMP_ACCESS_TOKEN}}

{
  "name": "Chase Sapphire",
  "type": "CreditCard"
}


GET {{BACKEND_URL}}/accounts
Content-Type: application/json
Authorization: Bearer {{TEMP_ACCESS_TOKEN}}


###
@id=d59d7f428b
GET {{BACKEND_URL}}/accounts/{{id}}
Content-Type: application/json
Authorization: Bearer {{TEMP_ACCESS_TOKEN}}

PUT {{BACKEND_URL}}/accounts/{{id}}
Content-Type: application/json
Authorization: Bearer {{TEMP_ACCESS_TOKEN}}

{
  "name": "Chase Sapphire 3"
}

GET {{BACKEND_URL}}/accounts/custom/my
Content-Type: application/json
Authorization: Bearer {{TEMP_ACCESS_TOKEN}}
