@username=touhidrahman3

###
POST {{BACKEND_URL}}/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "Abcd1234!"
}

###

POST {{BACKEND_URL}}/auth/register
Content-Type: application/json

{
  "firstName": "Touhid",
  "lastName": "Rahman",
  "username": "{{username}}",
  "password": "Abcd1234!"
}

###
