@resource=categories
@deleteId=b96dd738f1
@id=ebb65095bd

###
GET {{BACKEND_URL}}/core/{{resource}}
Content-Type: application/json
Authorization: Bearer {{TEMP_ACCESS_TOKEN}}


###
POST {{BACKEND_URL}}/core/{{resource}}
Content-Type: application/json
Authorization: Bearer {{TEMP_ACCESS_TOKEN}}

{
  "name": "Grocery",
  "color": "red"

}

###
POST {{BACKEND_URL}}/{{resource}}
Content-Type: application/json
Authorization: Bearer {{TEMP_ACCESS_TOKEN}}

{
  "name": "Grocery",
  "color": "red"
}


###
GET {{BACKEND_URL}}/{{resource}}
Content-Type: application/json
Authorization: Bearer {{TEMP_ACCESS_TOKEN}}


###
GET {{BACKEND_URL}}/{{resource}}/{{id}}
Content-Type: application/json
Authorization: Bearer {{TEMP_ACCESS_TOKEN}}


###
PUT {{BACKEND_URL}}/{{resource}}/{{id}}
Content-Type: application/json
Authorization: Bearer {{TEMP_ACCESS_TOKEN}}

{
  "title": "Grocery Shopping 3",
  "amount": "-3",
  "isOutgoing": true
}


###
DELETE {{BACKEND_URL}}/{{resource}}/{{deleteId}}
Content-Type: application/json
Authorization: Bearer {{TEMP_ACCESS_TOKEN}}


###
GET {{BACKEND_URL}}/{{resource}}/custom/my
Content-Type: application/json
Authorization: Bearer {{TEMP_ACCESS_TOKEN}}
