ALTER TABLE "invites" RENAME COLUMN "invited_by" TO "inviter_id";--> statement-breakpoint
CREATE INDEX "accounts_creator_id_idx" ON "accounts" ("creator_id");--> statement-breakpoint
CREATE INDEX "accounts_group_id_idx" ON "accounts" ("group_id");--> statement-breakpoint
CREATE INDEX "accounts_type_idx" ON "accounts" ("type");--> statement-breakpoint
CREATE INDEX "balance_transfer_schedules_creator_id_idx" ON "balance_transfer_schedules" ("creator_id");--> statement-breakpoint
CREATE INDEX "balance_transfer_schedules_group_id_idx" ON "balance_transfer_schedules" ("group_id");--> statement-breakpoint
CREATE INDEX "balance_transfer_schedules_from_account_id_idx" ON "balance_transfer_schedules" ("from_account_id");--> statement-breakpoint
CREATE INDEX "balance_transfer_schedules_to_account_id_idx" ON "balance_transfer_schedules" ("to_account_id");--> statement-breakpoint
CREATE INDEX "balance_transfer_schedules_category_id_idx" ON "balance_transfer_schedules" ("category_id");--> statement-breakpoint
CREATE INDEX "balance_transfer_schedules_subcategory_id_idx" ON "balance_transfer_schedules" ("subcategory_id");--> statement-breakpoint
CREATE INDEX "balance_transfers_creator_id_idx" ON "balance_transfers" ("creator_id");--> statement-breakpoint
CREATE INDEX "balance_transfers_group_id_idx" ON "balance_transfers" ("group_id");--> statement-breakpoint
CREATE INDEX "balance_transfers_from_account_id_idx" ON "balance_transfers" ("from_account_id");--> statement-breakpoint
CREATE INDEX "balance_transfers_to_account_id_idx" ON "balance_transfers" ("to_account_id");--> statement-breakpoint
CREATE INDEX "balance_transfers_category_id_idx" ON "balance_transfers" ("category_id");--> statement-breakpoint
CREATE INDEX "balance_transfers_subcategory_id_idx" ON "balance_transfers" ("subcategory_id");--> statement-breakpoint
CREATE INDEX "categories_creator_id_idx" ON "categories" ("creator_id");--> statement-breakpoint
CREATE INDEX "categories_group_id_idx" ON "categories" ("group_id");--> statement-breakpoint
CREATE INDEX "currencies_creator_id_idx" ON "currencies" ("creator_id");--> statement-breakpoint
CREATE INDEX "currencies_group_id_idx" ON "currencies" ("group_id");--> statement-breakpoint
CREATE INDEX "groups_creator_id_idx" ON "groups" ("creator_id");--> statement-breakpoint
CREATE INDEX "invites_inviter_id_idx" ON "invites" ("inviter_id");--> statement-breakpoint
CREATE INDEX "invites_group_id_idx" ON "invites" ("group_id");--> statement-breakpoint
CREATE INDEX "invites_role_id_idx" ON "invites" ("role_id");--> statement-breakpoint
CREATE INDEX "memberships_user_id_idx" ON "memberships" ("user_id");--> statement-breakpoint
CREATE INDEX "memberships_group_id_idx" ON "memberships" ("group_id");--> statement-breakpoint
CREATE INDEX "memberships_role_id_idx" ON "memberships" ("role_id");--> statement-breakpoint
CREATE INDEX "memberships_user_id_group_id_idx" ON "memberships" ("user_id","group_id");--> statement-breakpoint
CREATE INDEX "referrals_referral_code_id_idx" ON "referrals" ("referral_code_id");--> statement-breakpoint
CREATE INDEX "referrals_referred_id_idx" ON "referrals" ("referred_id");--> statement-breakpoint
CREATE INDEX "referral_codes_user_id_idx" ON "referral_codes" ("user_id");--> statement-breakpoint
CREATE INDEX "referral_codes_group_id_idx" ON "referral_codes" ("group_id");--> statement-breakpoint
CREATE INDEX "referral_codes_user_id_group_id_idx" ON "referral_codes" ("user_id","group_id");--> statement-breakpoint
CREATE INDEX "roles_group_id_idx" ON "roles" ("group_id");--> statement-breakpoint
CREATE INDEX "subcategories_group_id_idx" ON "subcategories" ("group_id");--> statement-breakpoint
CREATE INDEX "subcategories_creator_id_idx" ON "subcategories" ("creator_id");--> statement-breakpoint
CREATE INDEX "subcategories_category_id_idx" ON "subcategories" ("category_id");--> statement-breakpoint
CREATE INDEX "subscriptions_group_id_idx" ON "subscriptions" ("group_id");--> statement-breakpoint
CREATE INDEX "subscriptions_creator_id_idx" ON "subscriptions" ("creator_id");--> statement-breakpoint
CREATE INDEX "subscriptions_approver_id_idx" ON "subscriptions" ("approver_id");--> statement-breakpoint
CREATE INDEX "transaction_schedules_group_id_idx" ON "transaction_schedules" ("group_id");--> statement-breakpoint
CREATE INDEX "transaction_schedules_creator_id_idx" ON "transaction_schedules" ("creator_id");--> statement-breakpoint
CREATE INDEX "transaction_schedules_account_id_idx" ON "transaction_schedules" ("account_id");--> statement-breakpoint
CREATE INDEX "transactions_group_id_idx" ON "transactions" ("group_id");--> statement-breakpoint
CREATE INDEX "transactions_creator_id_idx" ON "transactions" ("creator_id");--> statement-breakpoint
CREATE INDEX "transactions_account_id_idx" ON "transactions" ("account_id");--> statement-breakpoint
CREATE INDEX "users_settings_user_id_idx" ON "users_settings" ("user_id");--> statement-breakpoint
CREATE INDEX "users_username_idx" ON "users" ("username");--> statement-breakpoint
CREATE INDEX "users_email_idx" ON "users" ("email");--> statement-breakpoint
CREATE INDEX "users_phone_idx" ON "users" ("phone");